### ISSUE TITLE
Task :smithy-typescript-codegen:compileJava when trying to build in develop branch

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy-typescript#2]
Steps followed:
* `git clone git@github.com:awslabs/smithy-typescript.git`
* `git checkout develop`
* `git log | head -5`
```console
commit badfc5ae941071e3744d0f761070155c96fa5fd6
Author: Michael Dowling <mtdowling@gmail.com>
Date:   Sat Sep 14 18:05:37 2019 -0700

    Apply minor code cleanup
```
* `./gradlew build --stacktrace`
```console
> Task :smithy-typescript-codegen:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smithy-typescript-codegen:compileJava'.
> Could not resolve all files for configuration ':smithy-typescript-codegen:compileClasspath'.
   > Could not find software.amazon.smithy:smithy-codegen-core:0.9.2.
     Searched in the following locations:
       - file:/Users/trivikr/.m2/repository/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.pom
       - file:/Users/trivikr/.m2/repository/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.jar
       - http://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.pom
       - http://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.jar
     Required by:
         project :smithy-typescript-codegen

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':smithy-typescript-codegen:compileJava'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':smithy-typescript-codegen:compileClasspath'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1258)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2200(DefaultConfiguration.java:139)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1233)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:75)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.iterator(DefaultConfiguration.java:486)
        at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter$FileCollectionLeafVisitorImpl.visitCollection(DefaultFileCollectionSnapshotter.java:60)
        at org.gradle.api.internal.file.AbstractFileCollection.visitLeafCollections(AbstractFileCollection.java:262)
        at org.gradle.api.internal.file.CompositeFileCollection.visitLeafCollections(CompositeFileCollection.java:205)
        at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:50)
        at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:46)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.lambda$visitInputFileProperties$0(ExecuteActionsTaskExecuter.java:283)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$fingerprintInputFiles$3(CaptureStateBeforeExecutionStep.java:154)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.visitInputFileProperties(ExecuteActionsTaskExecuter.java:281)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.fingerprintInputFiles(CaptureStateBeforeExecutionStep.java:150)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.createExecutionState(CaptureStateBeforeExecutionStep.java:114)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:67)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        ... 24 more
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find software.amazon.smithy:smithy-codegen-core:0.9.2.
Searched in the following locations:
  - file:/Users/trivikr/.m2/repository/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.pom
  - file:/Users/trivikr/.m2/repository/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.jar
  - http://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.pom
  - http://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.jar
Required by:
    project :smithy-typescript-codegen


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
```

**Comment by trivikr** [comment]
`./gradlew build --info`
```console
Initialized native services in: /Users/trivikr/.gradle/native
The client will now receive all logging from the daemon (pid: 57852). The daemon log file: /Users/trivikr/.gradle/daemon/5.6.2/daemon-57852.out.log
Starting 4th build in daemon [uptime: 10 mins 46.311 secs, performance: 99%, non-heap usage: 45% of 268.4 MB]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/Users/trivikr/workspace/smithy-typescript/settings.gradle.kts'.
Projects loaded. Root project using build file '/Users/trivikr/workspace/smithy-typescript/build.gradle.kts'.
Included projects: [root project 'smithy-typescript', project ':smithy-typescript-codegen', project ':smithy-typescript-codegen-test']

> Configure project :
Evaluating root project 'smithy-typescript' using build file '/Users/trivikr/workspace/smithy-typescript/build.gradle.kts'.

> Configure project :smithy-typescript-codegen
Evaluating project ':smithy-typescript-codegen' using build file '/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/build.gradle.kt
s'.

> Configure project :smithy-typescript-codegen-test
Evaluating project ':smithy-typescript-codegen-test' using build file '/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen-test/build
.gradle.kts'.
No Smithy model dependencies were found in the JAR, assuming Smithy CLI version 0.9.0
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':jar', task ':assemble', task ':checkstyleMain', task ':c
ompileTestJava', task ':processTestResources', task ':testClasses', task ':checkstyleTest', task ':spotbugsMain', task ':spotbugsTest', task ':test', 
task ':check', task ':build', task ':smithy-typescript-codegen:compileJava', task ':smithy-typescript-codegen:processResources', task ':smithy-typescr
ipt-codegen:classes', task ':smithy-typescript-codegen:jar', task ':smithy-typescript-codegen:assemble', task ':smithy-typescript-codegen:checkstyleMa
in', task ':smithy-typescript-codegen:compileTestJava', task ':smithy-typescript-codegen:processTestResources', task ':smithy-typescript-codegen:testC
lasses', task ':smithy-typescript-codegen:checkstyleTest', task ':smithy-typescript-codegen:spotbugsMain', task ':smithy-typescript-codegen:spotbugsTe
st', task ':smithy-typescript-codegen:test', task ':smithy-typescript-codegen:jacocoTestReport', task ':smithy-typescript-codegen:check', task ':smith
y-typescript-codegen:build', task ':smithy-typescript-codegen:javadoc', task ':smithy-typescript-codegen-test:smithyBuild', task ':smithy-typescript-c
odegen-test:compileJava', task ':smithy-typescript-codegen-test:processResources', task ':smithy-typescript-codegen-test:classes', task ':smithy-typescript-codegen-test:jar', task ':smithy-typescript-codegen-test:assemble', task ':smithy-typescript-codegen-test:compileTestJava', task ':smithy-typescript-codegen-test:processTestResources', task ':smithy-typescript-codegen-test:testClasses', task ':smithy-typescript-codegen-test:test', task ':smithy-typescript-codegen-test:check', task ':smithy-typescript-codegen-test:build']
:compileJava (Thread[Execution worker for ':',5,main]) started.

> Task :compileJava NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/main/java', not found
Skipping task ':compileJava' as it has no source files and no previous output files.
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.005 secs.
:processResources (Thread[Execution worker for ':',5,main]) started.

> Task :processResources NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/main/resources', not found
Skipping task ':processResources' as it has no source files and no previous output files.
:processResources (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:classes (Thread[Execution worker for ':',5,main]) started.

> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.
:classes (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:jar (Thread[Execution worker for ':',5,main]) started.

> Task :jar SKIPPED
Skipping task ':jar' as task onlyIf is false.
:jar (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:assemble (Thread[Execution worker for ':',5,main]) started.

> Task :assemble UP-TO-DATE
Skipping task ':assemble' as it has no actions.
:assemble (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:checkstyleMain (Thread[Execution worker for ':',5,main]) started.

> Task :checkstyleMain NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/main/java', not found
Skipping task ':checkstyleMain' as it has no source files and no previous output files.
:checkstyleMain (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:compileTestJava (Thread[Execution worker for ':',5,main]) started.

> Task :compileTestJava NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/test/java', not found
Skipping task ':compileTestJava' as it has no source files and no previous output files.
:compileTestJava (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:processTestResources (Thread[Execution worker for ':',5,main]) started.

> Task :processTestResources NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/test/resources', not found
Skipping task ':processTestResources' as it has no source files and no previous output files.
:processTestResources (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:testClasses (Thread[Execution worker for ':',5,main]) started.

> Task :testClasses UP-TO-DATE
Skipping task ':testClasses' as it has no actions.
:testClasses (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:checkstyleTest (Thread[Execution worker for ':',5,main]) started.

> Task :checkstyleTest NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/test/java', not found
Skipping task ':checkstyleTest' as it has no source files and no previous output files.
:checkstyleTest (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:spotbugsMain (Thread[Execution worker for ':',5,main]) started.

> Task :spotbugsMain NO-SOURCE
Skipping task ':spotbugsMain' as it has no source files and no previous output files.
:spotbugsMain (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:spotbugsTest (Thread[Execution worker for ':',5,main]) started.

> Task :spotbugsTest NO-SOURCE
Skipping task ':spotbugsTest' as it has no source files and no previous output files.
:spotbugsTest (Thread[Execution worker for ':',5,main]) completed. Took 0.002 secs.
:test (Thread[Execution worker for ':',5,main]) started.

> Task :test NO-SOURCE
Skipping task ':test' as it has no source files and no previous output files.
:test (Thread[Execution worker for ':',5,main]) completed. Took 0.004 secs.
:check (Thread[Execution worker for ':',5,main]) started.

> Task :check UP-TO-DATE
Skipping task ':check' as it has no actions.
:check (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:build (Thread[Execution worker for ':',5,main]) started.

> Task :build UP-TO-DATE
Skipping task ':build' as it has no actions.
:build (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:smithy-typescript-codegen:compileJava (Thread[Execution worker for ':',5,main]) started.

> Task :smithy-typescript-codegen:compileJava FAILED
Resource missing. [HTTP GET: http://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.pom]
Resource missing. [HTTP HEAD: http://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.jar]
:smithy-typescript-codegen:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.048 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smithy-typescript-codegen:compileJava'.
> Could not resolve all files for configuration ':smithy-typescript-codegen:compileClasspath'.
   > Could not find software.amazon.smithy:smithy-codegen-core:0.9.2.
     Searched in the following locations:
       - file:/Users/trivikr/.m2/repository/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.pom
       - file:/Users/trivikr/.m2/repository/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.jar
       - http://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.pom
       - http://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-codegen-core/0.9.2/smithy-codegen-core-0.9.2.jar
     Required by:
         project :smithy-typescript-codegen

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
```

**Comment by trivikr** [comment]
build scan can be viewed at https://scans.gradle.com/s/way444ejojexw

**Comment by mtdowling** [comment]
Should be fixed by https://github.com/awslabs/smithy-typescript/commit/f3a55998543798ed874fab830d91bb5685a38143
