### ISSUE TITLE
fetch-http-handler incompatible with undici

### ISSUE THREAD

**Issue by bestickley** [awslabs/smithy-typescript#982]
Hi,

I'm using [undici](https://undici.nodejs.org/#/) in my Node.js project to properly get type safety (see more [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924) for why). When I did that, I ran into an issue using the AWS SDK JS V3 RDS Signer where the root issue is in the fetch-http-handler package in this repo. Specifically, the line below:

https://github.com/awslabs/smithy-typescript/blob/c607f6c2dffbdbf4043a68b9ba98434ec2367d29/packages/fetch-http-handler/src/fetch-http-handler.ts#L32

The error I got was:
```bash
node:internal/deps/undici/undici:7134
            throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^

TypeError: Failed to parse URL from
    at new Request (node:internal/deps/undici/undici:7134:19)
    at body (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@smithy+fetch-http-handler@2.2.0/node_modules/@smithy/fetch-http-handler/dist-cjs/fetch-http-handler.js:8:73)
    ... 7 lines matching cause stack trace ...
    at <anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@smithy+fetch-http-handler@2.2.0/node_modules/@smithy/fetch-http-handler/dist-cjs/index.js:4:22) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:637:13)
      at new Request (node:internal/deps/undici/undici:7132:25)
      at body (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@smithy+fetch-http-handler@2.2.0/node_modules/@smithy/fetch-http-handler/dist-cjs/fetch-http-handler.js:8:73)
      at Object.<anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@smithy+fetch-http-handler@2.2.0/node_modules/@smithy/fetch-http-handler/dist-cjs/fetch-http-handler.js:115:28)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.S (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at <anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@smithy+fetch-http-handler@2.2.0/node_modules/@smithy/fetch-http-handler/dist-cjs/index.js:4:22)
      at Object.<anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@smithy+fetch-http-handler@2.2.0/node_modules/@smithy/fetch-http-handler/dist-cjs/index.js:5:60)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.S (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at <anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+credential-provider-http@3.422.0/node_modules/@aws-sdk/credential-provider-http/dist-cjs/fromHttp/fromHttp.browser.js:4:30)
      at Object.<anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+credential-provider-http@3.422.0/node_modules/@aws-sdk/credential-provider-http/dist-cjs/fromHttp/fromHttp.browser.js:31:20)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.S (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at <anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+credential-provider-http@3.422.0/node_modules/@aws-sdk/credential-provider-http/dist-cjs/index.js:6:26)
      at Object.<anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+credential-provider-http@3.422.0/node_modules/@aws-sdk/credential-provider-http/dist-cjs/index.js:7:132)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.S (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at <anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+credential-providers@3.422.0/node_modules/@aws-sdk/credential-providers/dist-cjs/index.js:9:34)
      at Object.<anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+credential-providers@3.422.0/node_modules/@aws-sdk/credential-providers/dist-cjs/index.js:18:56)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.S (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at <anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+rds-signer@3.422.1/node_modules/@aws-sdk/rds-signer/dist-cjs/runtimeConfig.js:4:32)
      at Object.<anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+rds-signer@3.422.1/node_modules/@aws-sdk/rds-signer/dist-cjs/runtimeConfig.js:18:28)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.S (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at <anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+rds-signer@3.422.1/node_modules/@aws-sdk/rds-signer/dist-cjs/Signer.js:7:25)
      at Object.<anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+rds-signer@3.422.1/node_modules/@aws-sdk/rds-signer/dist-cjs/Signer.js:46:18)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.S (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at <anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+rds-signer@3.422.1/node_modules/@aws-sdk/rds-signer/dist-cjs/index.js:4:22)
      at Object.<anonymous> (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/@aws-sdk+rds-signer@3.422.1/node_modules/@aws-sdk/rds-signer/dist-cjs/index.js:4:50)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.S (/Users/stickb/Code/scratch/cpg1/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
    input: '',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.18.0
```

I temporarily fixed this by adding a valid url in the `Request` constructor like: `new Request("https://amazon.com")`. Could something like this be done? URL is arbitrary, just needs to be valid.

**Comment by bestickley** [comment]
Looking into this issue more, I don't think it's because I added the `undici` package, I think it may be any version Node.js 18 with `fetch` based on the path above, `node:internal/deps/undici/undici:7134`.

I think [this issue](https://github.com/aws/aws-sdk-js-v3/issues/4619) may be related as well. In that issue, it is suggested to use the node-http-handler which may be the correct fix as apparently fetch-http-handler is meant to be used in browser. I'm not sure where that package should replace fetch-http-handler in the chain of function calls shows above.
